# Change these first
owner: totavok8 # Your GitHub organization or username, where this repository lives
repo: uptime_kulik # The name of this repository

sites:
  - name: Kulik House
    url: http://cloud.kulik.uz/
  - name: Plugin Kulik
    url: http://cdn.kulik.uz/
  - name: RU-Server
    url: http://ruclast.kulik.uz/
  - name: DE-Server
    url: http://deuts-cdn.kulik.uz/

status-website:
  cname: uptime.kulik.uz
  favicon: https://raw.githubusercontent.com/totavok8/uptime_kulik/master/logo.png
  baseUrl: /
  logoUrl: https://raw.githubusercontent.com/totavok8/uptime_kulik/master/logo.png
  name: Kulik
  introTitle: "**Kulik** status"
  introMessage: This is a status page which uses **real-time** data from our servers
  navbar:
    - title: Status
      href: /
i18n:
  footer: '[https://t.me/lampa_channels](https://t.me/lampa_channels)'
  incidentViewOnGitHub: ''
